### ISSUE TITLE
Certificate installation and savon usage

### ISSUE THREAD

**Issue by viniciusnz** [iugu/nfe-paulistana#5]
Thanks a lot for this gem, Iugu!

For those with problems getting to access the nfe servers, don't forget to download the ca-certificates and install them to the system like explained in, for example, 

https://help.ubuntu.com/community/OpenSSL

I also had trouble using curb as the HTTPI interface, so I had to used net_http. One can do that with:

`HTTPI.adapter = :net_http`

I hope this helps people not spend the hours I spent debugging other stuff.

All the best,

**Comment by cirdes** [comment]
```
HTTPI.adapter = :net_http
```
Saved me!
