### ISSUE TITLE
Essa gem é para Nota Fiscal de SERVIÇO Eletrônica?

### ISSUE THREAD

**Issue by adrianomargarin** [iugu/nfe-paulistana#9]
Essa gem é para Nota Fiscal de SERVIÇO Eletrônica (NFSe) ou para Nota Fiscal Eletrônica (NFe)?

**Comment by alepaez** [comment]
Oi Adriano.

Essa gem é para integrar com a nota fiscal paulistana. http://nfpaulistana.prefeitura.sp.gov.br/

**Comment by adrianomargarin** [comment]
Obrigado Alexandre. Podemos trocar alguns e-mails sobre a gem? Estou implementando em python a integração com SP e estou com problema na Signature e estou me baseando nessa gem para fazer a integração. Para não fica chato nas issue tirar essas dúvidas poderia me mandar um e-mail do seu particular? PS. Meu e-mail está no meu perfil do github. Obrigado pela atenção.
